development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
  username: testdatabase
  password: passwordtest


test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: testdatabase
  password: passwordtest 